[package]
name = "rusty_hacker"
version = "0.1.0"
authors = ["kade killary <kadekillary@protonmail.com>"]

[dependencies]
reqwest = "*"
select = "*"
scraper = "*"
prettytable-rs = "*"
openssl-sys = "0.9.39"
openssl="0.10"
feed-rs="0.1.3"
atom_syndication="*"
tempfile="*"
num_cpus="*"